EncodeParams:
  context: AVCodecContext
  members:
      - [int64_t, bit_rate]
      - [std::string, pix_fmt, set_pix_fmt_template, get_pix_fmt_template]
      - [std::string, sample_fmt, set_sample_fmt_template, get_sample_fmt_template]
      # audio only
      - [int, channels]
      - [int, sample_rate]
      # video only
      - [int, width] # resolution must be a multiple of two
      - [int, height]
      - [AVRational, framerate]
      - [AVRational, time_base]
      - [int, keyint_min]
      - [int, gop_size]
      - [int, max_b_frames]

FrameParams:
  context: AVFrame
  members:
    - [int64_t, pts]
    - [std::string, format, set_AVFrameFormat, get_AVFrameFormat] # video (pixel format); audio (sample format)
      # video only
    - [int, width]
    - [int, height]

StreamParams:
  context: AVStream
  members:
    - [AVRational, time_base]

CodecParams:
  context: AVCodecParameters
  members:
    - [int32_t, codec_id, set_codec_id_template, get_codec_id_template]
    - [int64_t, bit_rate]
    # video only
    # audio only
    - [int, sample_rate]
    - [int, channels]
    # - [std::string, channel_layout, set_channel_layout]

PacketParams:
  context: AVPacket
  members:
    - [int, stream_index]